apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
          app: myapp
          type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2
  #what pods fall under replica set
  #replicaset can also manage pods which are not part of the replica set
  #!!!required!!!
  selector:
    matchLabels:
      type: front-end
